import { v4 as uuid } from 'uuid';
import bcrypt from 'bcryptjs';
import type { User, Project, AlertItem, ProjectFeedback } from './types.js';

const today = new Date();
const iso = (offsetDays: number) => {
  const d = new Date();
  d.setDate(d.getDate() + offsetDays);
  return d.toISOString();
};

export const demoUsers: User[] = [
  {
    id: 'u-admin',
    name: 'System Administrator',
    email: 'admin@projectpulse.demo',
    password: bcrypt.hashSync('admin123', 10),
    role: 'admin',
    department: 'Administration',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'u-officer',
    name: 'Rural Development Officer',
    email: 'officer@projectpulse.demo',
    password: bcrypt.hashSync('officer123', 10),
    role: 'officer',
    department: 'Rural Development',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'u-contractor',
    name: 'Urban Build Contractors',
    email: 'contractor@projectpulse.demo',
    password: bcrypt.hashSync('contractor123', 10),
    role: 'contractor',
    department: 'Infrastructure',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'u-citizen',
    name: 'Citizen Reporter',
    email: 'citizen@projectpulse.demo',
    password: bcrypt.hashSync('citizen123', 10),
    role: 'citizen',
    department: 'Public',
    createdAt: new Date().toISOString(),
  },
];

const makeMilestone = (
  name: string,
  description: string,
  start: number,
  due: number,
  completion: number,
  status: 'Pending' | 'In Progress' | 'Completed' | 'Delayed',
  responsible: string,
) => ({
  id: uuid(),
  name,
  description,
  startDate: iso(start),
  dueDate: iso(due),
  completion,
  status,
  responsible,
});

const makeIssue = (
  title: string,
  description: string,
  priority: 'Low' | 'Medium' | 'High' | 'Critical',
  status: 'Open' | 'In Review' | 'Resolved',
  reportedBy: string,
  createdOffset: number,
  resolution?: string,
) => ({
  id: uuid(),
  title,
  description,
  priority,
  status,
  reportedBy,
  createdAt: iso(createdOffset),
  resolution,
});

const makeProgressUpdate = (progress: number, description: string, photoUrl: string, updatedBy: string, offset: number) => ({
  id: uuid(),
  progress,
  description,
  photoUrl,
  updatedBy,
  createdAt: iso(offset),
});

const makeExpense = (amount: number, category: string, description: string, dayOffset: number, approvedBy: string) => ({
  id: uuid(),
  amount,
  category,
  description,
  date: iso(dayOffset),
  approvedBy,
});

const makeDocument = (name: string, fileUrl: string, uploadedBy: string, offset: number) => ({
  id: uuid(),
  name,
  fileUrl,
  uploadedBy,
  uploadedAt: iso(offset),
});

export const demoProjects: Project[] = [
  {
    id: 'p-101',
    projectCode: 'PP-101',
    name: 'Rural Road Development Project',
    description: 'Upgradation of rural roads to improve local connectivity and reduce travel time.',
    department: 'Rural Development',
    category: 'Road Infrastructure',
    state: 'Karnataka',
    district: 'Bengaluru Rural',
    location: 'Kanakapura Road',
    latitude: 12.8737,
    longitude: 77.5668,
    budget: 4500000,
    expenditure: 3100000,
    progress: 72,
    status: 'In Progress',
    startDate: iso(-220),
    expectedEndDate: iso(22),
    actualEndDate: undefined,
    managerId: 'u-officer',
    contractorId: 'u-contractor',
    createdAt: iso(-240),
    milestones: [
      makeMilestone('Survey & Planning', 'Topographic survey and route confirmation', -180, -120, 100, 'Completed', 'Officer'),
      makeMilestone('Land Acquisition', 'Land verification and transfer documentation', -120, -60, 85, 'Completed', 'Project Team'),
      makeMilestone('Earthwork & Drainage', 'Road base and side drainage works', -40, 20, 68, 'In Progress', 'Contractor'),
      makeMilestone('Bitumen Surfacing', 'Bitumen layer and lane markings', 0, 45, 42, 'Delayed', 'Contractor'),
    ],
    issues: [
      makeIssue('Material supply delay', 'Supplier delayed bitumen delivery affecting schedule', 'High', 'Open', 'Officer', -10),
      makeIssue('Drainage issue', 'Drainage work in one stretch needs rework', 'Medium', 'In Review', 'Citizen', -3),
    ],
    documents: [
      makeDocument('Project Proposal', 'https://example.com/proposal-road.pdf', 'officer@projectpulse.demo', -200),
      makeDocument('Tender Document', 'https://example.com/tender-road.pdf', 'admin@projectpulse.demo', -170),
    ],
    progressUpdates: [
      makeProgressUpdate(60, 'Road base completed across 60% of the stretch', 'https://images.unsplash.com/...', 'officer@projectpulse.demo', -15),
      makeProgressUpdate(72, 'Drainage works completed and inspection passed', 'https://images.unsplash.com/...', 'contractor@projectpulse.demo', -3),
    ],
    expenses: [
      makeExpense(1100000, 'Earthwork', 'Soil filling and grading work', -90, 'officer@projectpulse.demo'),
      makeExpense(950000, 'Drainage', 'Culvert installation and drainage', -25, 'officer@projectpulse.demo'),
      makeExpense(800000, 'Material', 'Bitumen and aggregate supply', -4, 'contractor@projectpulse.demo'),
    ],
    risk: {
      level: 'High',
      score: 78,
      reasons: ['Milestone completion is behind schedule', 'Multiple issues remain unresolved', 'Budget utilization is above plan'],
      daysRemaining: 18,
      delayDays: 11,
      unresolvedIssues: 2,
    },
  },
  {
    id: 'p-102',
    projectCode: 'PP-102',
    name: 'Government School Renovation',
    description: 'Structural renovation and classroom modernization for a government secondary school.',
    department: 'Education',
    category: 'School Infrastructure',
    state: 'Tamil Nadu',
    district: 'Coimbatore',
    location: 'Pollachi Taluk',
    latitude: 10.6591,
    longitude: 77.0117,
    budget: 2800000,
    expenditure: 1800000,
    progress: 81,
    status: 'In Progress',
    startDate: iso(-180),
    expectedEndDate: iso(16),
    actualEndDate: undefined,
    managerId: 'u-officer',
    contractorId: 'u-contractor',
    createdAt: iso(-200),
    milestones: [
      makeMilestone('Tender Award', 'Tender released and contractor selected', -150, -120, 100, 'Completed', 'Education Dept'),
      makeMilestone('Civil Repair Works', 'Roofing and structural repair', -90, -30, 85, 'Completed', 'Contractor'),
      makeMilestone('Interior Upgrade', 'Classroom fitout and furniture', -30, 12, 77, 'In Progress', 'Contractor'),
      makeMilestone('Handover', 'Final inspection and completion', 12, 30, 26, 'Pending', 'Officer'),
    ],
    issues: [
      makeIssue('Roof leak investigation', 'Leak in one segment of the school roof', 'Medium', 'Resolved', 'Officer', -50, 'Patch repair completed'),
    ],
    documents: [
      makeDocument('Architect Plan', 'https://example.com/school-plan.pdf', 'officer@projectpulse.demo', -170),
      makeDocument('Inspection Report', 'https://example.com/school-inspection.pdf', 'admin@projectpulse.demo', -30),
    ],
    progressUpdates: [
      makeProgressUpdate(68, 'Classroom refurbishment completed in 4 blocks', 'https://images.unsplash.com/...', 'contractor@projectpulse.demo', -8),
      makeProgressUpdate(81, 'Final electrical fixtures being installed', 'https://images.unsplash.com/...', 'officer@projectpulse.demo', -1),
    ],
    expenses: [
      makeExpense(640000, 'Civil Works', 'Roof repairs and masonry', -95, 'officer@projectpulse.demo'),
      makeExpense(510000, 'Interior', 'Classroom partitioning and paint', -30, 'officer@projectpulse.demo'),
      makeExpense(320000, 'Electrical', 'Lighting and wiring', -4, 'contractor@projectpulse.demo'),
    ],
    risk: {
      level: 'Medium',
      score: 54,
      reasons: ['Budget utilization is moderate', 'One milestone requires final inspection'],
      daysRemaining: 15,
      delayDays: 3,
      unresolvedIssues: 1,
    },
  },
  {
    id: 'p-103',
    projectCode: 'PP-103',
    name: 'Village Drinking Water Supply Project',
    description: 'Installation of water supply pipelines and storage tanks for rural habitations.',
    department: 'Water Resources',
    category: 'Water Supply',
    state: 'Karnataka',
    district: 'Bengaluru Rural',
    location: 'Hoskote',
    latitude: 13.0717,
    longitude: 77.8081,
    budget: 4500000,
    expenditure: 3050000,
    progress: 68,
    status: 'In Progress',
    startDate: iso(-260),
    expectedEndDate: iso(28),
    actualEndDate: undefined,
    managerId: 'u-officer',
    contractorId: 'u-contractor',
    createdAt: iso(-270),
    milestones: [
      makeMilestone('Pipeline Survey', 'Hydrological survey and route mapping', -210, -170, 100, 'Completed', 'Field Team'),
      makeMilestone('Tank Foundation', 'Tank construction and base work', -140, -70, 80, 'Completed', 'Contractor'),
      makeMilestone('Pipe Laying', 'Pipeline extension and fittings', -60, 20, 67, 'In Progress', 'Contractor'),
      makeMilestone('Commissioning', 'Distribution testing and handover', 12, 45, 35, 'Pending', 'Officer'),
    ],
    issues: [
      makeIssue('Water quality test pending', 'Need final parameter testing before handover', 'High', 'Open', 'Officer', -2),
    ],
    documents: [
      makeDocument('Site Survey', 'https://example.com/water-survey.pdf', 'officer@projectpulse.demo', -200),
      makeDocument('Material Invoice', 'https://example.com/water-invoice.pdf', 'contractor@projectpulse.demo', -18),
    ],
    progressUpdates: [
      makeProgressUpdate(58, 'Pipeline work completed in 2 villages', 'https://images.unsplash.com/...', 'contractor@projectpulse.demo', -9),
      makeProgressUpdate(68, 'Testing and leakage checks initiated', 'https://images.unsplash.com/...', 'officer@projectpulse.demo', -2),
    ],
    expenses: [
      makeExpense(1200000, 'Pipeline', 'PVC and HDPE pipe supply', -110, 'officer@projectpulse.demo'),
      makeExpense(880000, 'Tank Works', 'Storage tank construction', -40, 'contractor@projectpulse.demo'),
      makeExpense(450000, 'Testing', 'Quality testing and certification', -5, 'officer@projectpulse.demo'),
    ],
    risk: {
      level: 'Medium',
      score: 62,
      reasons: ['Final commissioning is pending', 'Quality test is outstanding'],
      daysRemaining: 27,
      delayDays: 5,
      unresolvedIssues: 1,
    },
  },
  {
    id: 'p-104',
    projectCode: 'PP-104',
    name: 'Rural Health Centre Construction',
    description: 'Construction of a rural primary health centre with waiting area and utility rooms.',
    department: 'Health',
    category: 'Healthcare Infrastructure',
    state: 'Maharashtra',
    district: 'Nashik',
    location: 'Sinnar',
    latitude: 19.877,
    longitude: 74.001,
    budget: 3300000,
    expenditure: 2600000,
    progress: 92,
    status: 'Completed',
    startDate: iso(-230),
    expectedEndDate: iso(-8),
    actualEndDate: iso(-4),
    managerId: 'u-officer',
    contractorId: 'u-contractor',
    createdAt: iso(-250),
    milestones: [
      makeMilestone('Site Preparation', 'Site clearing and staging', -200, -170, 100, 'Completed', 'Field Team'),
      makeMilestone('Foundation Works', 'Concrete work and structural beams', -150, -100, 100, 'Completed', 'Contractor'),
      makeMilestone('Medical Facilities', 'Installation of rooms and fixtures', -90, -20, 100, 'Completed', 'Officer'),
      makeMilestone('Final Handover', 'Inspection and occupancy', -30, -4, 100, 'Completed', 'Officer'),
    ],
    issues: [
      makeIssue('Minor finishing adjustments', 'A few touch-ups pending before handover', 'Low', 'Resolved', 'Officer', -10, 'Completed before opening'),
    ],
    documents: [
      makeDocument('Completion Certificate', 'https://example.com/health-certificate.pdf', 'officer@projectpulse.demo', -5),
      makeDocument('Inspection Report', 'https://example.com/health-inspection.pdf', 'admin@projectpulse.demo', -7),
    ],
    progressUpdates: [
      makeProgressUpdate(90, 'Health centre nearly ready for inauguration', 'https://images.unsplash.com/...', 'officer@projectpulse.demo', -12),
      makeProgressUpdate(92, 'Final safety inspection completed', 'https://images.unsplash.com/...', 'contractor@projectpulse.demo', -5),
    ],
    expenses: [
      makeExpense(980000, 'Civil Works', 'Foundation and superstructure', -120, 'officer@projectpulse.demo'),
      makeExpense(470000, 'Medical Genset', 'Power backup installation', -44, 'officer@projectpulse.demo'),
      makeExpense(630000, 'Finishes', 'Interior fitout and painting', -15, 'officer@projectpulse.demo'),
    ],
    risk: {
      level: 'Low',
      score: 16,
      reasons: ['Project is near completion and no critical issues remain'],
      daysRemaining: 0,
      delayDays: 0,
      unresolvedIssues: 0,
    },
  },
  {
    id: 'p-105',
    projectCode: 'PP-105',
    name: 'Solar Street Lighting Project',
    description: 'Deployment of solar lighting systems across village roads and public spaces.',
    department: 'Energy',
    category: 'Renewable Energy',
    state: 'Gujarat',
    district: 'Rajkot',
    location: 'Lodhika',
    latitude: 22.3039,
    longitude: 70.8022,
    budget: 1800000,
    expenditure: 1450000,
    progress: 76,
    status: 'On Hold',
    startDate: iso(-170),
    expectedEndDate: iso(26),
    actualEndDate: undefined,
    managerId: 'u-officer',
    contractorId: 'u-contractor',
    createdAt: iso(-180),
    milestones: [
      makeMilestone('Site Survey', 'Lighting feasibility and pole mapping', -150, -120, 100, 'Completed', 'Field Team'),
      makeMilestone('Pole Installation', 'Street poles and mounting', -90, -40, 70, 'In Progress', 'Contractor'),
      makeMilestone('Panel Wiring', 'Solar panel unit connection', -20, 25, 45, 'On Hold', 'Contractor'),
    ],
    issues: [
      makeIssue('Battery supply shortage', 'Lead time for solar battery units is longer than expected', 'Critical', 'Open', 'Contractor', -6),
      makeIssue('Funding reallocation request', 'Procurement budget review pending', 'High', 'In Review', 'Officer', -2),
    ],
    documents: [
      makeDocument('Feasibility Report', 'https://example.com/solar-feasibility.pdf', 'officer@projectpulse.demo', -160),
      makeDocument('Procurement Order', 'https://example.com/solar-order.pdf', 'contractor@projectpulse.demo', -15),
    ],
    progressUpdates: [
      makeProgressUpdate(71, 'Pole installation reached 70% coverage', 'https://images.unsplash.com/...', 'contractor@projectpulse.demo', -11),
      makeProgressUpdate(76, 'On-hold due to battery supply issue', 'https://images.unsplash.com/...', 'officer@projectpulse.demo', -4),
    ],
    expenses: [
      makeExpense(620000, 'Poles', 'Streetlight poles and fittings', -90, 'officer@projectpulse.demo'),
      makeExpense(410000, 'Panels', 'Solar panel units', -32, 'contractor@projectpulse.demo'),
      makeExpense(270000, 'Wiring', 'Connection and control box work', -8, 'officer@projectpulse.demo'),
    ],
    risk: {
      level: 'Critical',
      score: 91,
      reasons: ['Critical material shortage is delaying completion', 'Project has been placed on hold', 'Unresolved procurement issue remains active'],
      daysRemaining: 26,
      delayDays: 17,
      unresolvedIssues: 2,
    },
  },
  {
    id: 'p-106',
    projectCode: 'PP-106',
    name: 'Community Hall Development',
    description: 'Construction of a multipurpose community hall for local events and public gatherings.',
    department: 'Urban Development',
    category: 'Public Facilities',
    state: 'Andhra Pradesh',
    district: 'Vijayawada',
    location: 'Tadepalli',
    latitude: 16.495,
    longitude: 80.6406,
    budget: 2100000,
    expenditure: 1700000,
    progress: 63,
    status: 'Delayed',
    startDate: iso(-140),
    expectedEndDate: iso(10),
    actualEndDate: undefined,
    managerId: 'u-officer',
    contractorId: 'u-contractor',
    createdAt: iso(-160),
    milestones: [
      makeMilestone('Structural Works', 'Columns, slabs and roof structure', -120, -40, 85, 'Completed', 'Contractor'),
      makeMilestone('Plastering', 'Walls, ceilings and internal plaster', -50, 15, 60, 'Delayed', 'Contractor'),
      makeMilestone('Landscaping', 'Outer work and site finishing', 0, 25, 30, 'Pending', 'Contractor'),
    ],
    issues: [
      makeIssue('Workforce shortage', 'Labour shortage has caused schedule slippage', 'High', 'Open', 'Contractor', -8),
    ],
    documents: [
      makeDocument('Design Plan', 'https://example.com/community-hall-plan.pdf', 'officer@projectpulse.demo', -150),
      makeDocument('Progress Invoice', 'https://example.com/community-hall-invoice.pdf', 'contractor@projectpulse.demo', -24),
    ],
    progressUpdates: [
      makeProgressUpdate(58, 'Structural works completed and wall finishing underway', 'https://images.unsplash.com/...', 'contractor@projectpulse.demo', -9),
      makeProgressUpdate(63, 'Labour shortage affecting finishing works', 'https://images.unsplash.com/...', 'officer@projectpulse.demo', -3),
    ],
    expenses: [
      makeExpense(710000, 'Structural Work', 'Columns and beams', -95, 'officer@projectpulse.demo'),
      makeExpense(520000, 'Plastering', 'Wall and ceiling finish', -22, 'officer@projectpulse.demo'),
      makeExpense(310000, 'Landscaping', 'Outer works and site improvement', -4, 'contractor@projectpulse.demo'),
    ],
    risk: {
      level: 'High',
      score: 77,
      reasons: ['Milestone delay due to labour shortage', 'Project completion is behind timeline'],
      daysRemaining: 10,
      delayDays: 8,
      unresolvedIssues: 1,
    },
  },
  {
    id: 'p-107',
    projectCode: 'PP-107',
    name: 'Drainage Improvement Project',
    description: 'Stormwater and sewer line upgrade for urban drainage resilience.',
    department: 'Municipal Works',
    category: 'Urban Drainage',
    state: 'West Bengal',
    district: 'Kolkata',
    location: 'Bidhannagar',
    latitude: 22.5796,
    longitude: 88.4334,
    budget: 5200000,
    expenditure: 3600000,
    progress: 70,
    status: 'In Progress',
    startDate: iso(-250),
    expectedEndDate: iso(32),
    actualEndDate: undefined,
    managerId: 'u-officer',
    contractorId: 'u-contractor',
    createdAt: iso(-270),
    milestones: [
      makeMilestone('Survey & Mapping', 'Survey and route planning', -220, -160, 100, 'Completed', 'Engineer Team'),
      makeMilestone('Trench Works', 'Excavation and pipe laying', -120, -40, 78, 'Completed', 'Contractor'),
      makeMilestone('Final Drainage Connection', 'Linking drains and retention', -30, 20, 52, 'In Progress', 'Contractor'),
    ],
    issues: [
      makeIssue('Traffic diversion issue', 'Road closure plan needs update', 'Medium', 'Open', 'Officer', -5),
    ],
    documents: [
      makeDocument('Survey Map', 'https://example.com/drainage-map.pdf', 'officer@projectpulse.demo', -220),
      makeDocument('Work Order', 'https://example.com/drainage-work-order.pdf', 'admin@projectpulse.demo', -150),
    ],
    progressUpdates: [
      makeProgressUpdate(66, 'Drain line connections completed in 3 sectors', 'https://images.unsplash.com/...', 'contractor@projectpulse.demo', -8),
      makeProgressUpdate(70, 'Final trench works and route checks continue', 'https://images.unsplash.com/...', 'officer@projectpulse.demo', -2),
    ],
    expenses: [
      makeExpense(1500000, 'Excavation', 'Trench and clearing works', -110, 'officer@projectpulse.demo'),
      makeExpense(1200000, 'Pipes', 'Drainage pipe and fittings', -26, 'officer@projectpulse.demo'),
      makeExpense(700000, 'Traffic Management', 'Diversion and road safety', -7, 'contractor@projectpulse.demo'),
    ],
    risk: {
      level: 'Medium',
      score: 58,
      reasons: ['Schedule remains moderate with pending final connection'],
      daysRemaining: 30,
      delayDays: 4,
      unresolvedIssues: 1,
    },
  },
  {
    id: 'p-108',
    projectCode: 'PP-108',
    name: 'Rural Bridge Construction',
    description: 'Construct a small-span rural bridge to improve access to remote villages.',
    department: 'Public Works',
    category: 'Bridge Infrastructure',
    state: 'Odisha',
    district: 'Cuttack',
    location: 'Mohana',
    latitude: 20.4161,
    longitude: 85.9356,
    budget: 6700000,
    expenditure: 5000000,
    progress: 58,
    status: 'Delayed',
    startDate: iso(-300),
    expectedEndDate: iso(18),
    actualEndDate: undefined,
    managerId: 'u-officer',
    contractorId: 'u-contractor',
    createdAt: iso(-320),
    milestones: [
      makeMilestone('Foundation Works', 'Piling and abutment setup', -250, -160, 100, 'Completed', 'Contractor'),
      makeMilestone('Deck Construction', 'Girder support and bridge deck', -120, -30, 62, 'Delayed', 'Contractor'),
      makeMilestone('Safety Testing', 'Load test and final inspection', -5, 24, 20, 'Pending', 'Officer'),
    ],
    issues: [
      makeIssue('Weather disruption', 'Monsoon interruption slowed bridge deck work', 'High', 'Open', 'Officer', -12),
      makeIssue('Quality check failure', 'Concrete slab reinforcement needed rework', 'Critical', 'Open', 'Contractor', -4),
    ],
    documents: [
      makeDocument('Geotechnical Report', 'https://example.com/bridge-geo.pdf', 'officer@projectpulse.demo', -240),
      makeDocument('Material Test Report', 'https://example.com/bridge-material.pdf', 'contractor@projectpulse.demo', -6),
    ],
    progressUpdates: [
      makeProgressUpdate(52, 'Deck formwork delayed by monsoon conditions', 'https://images.unsplash.com/...', 'contractor@projectpulse.demo', -10),
      makeProgressUpdate(58, 'Reinforcement rework underway to meet strength standards', 'https://images.unsplash.com/...', 'officer@projectpulse.demo', -4),
    ],
    expenses: [
      makeExpense(2100000, 'Foundation', 'Piles and abutments', -160, 'officer@projectpulse.demo'),
      makeExpense(1650000, 'Deck', 'Girder and slab work', -42, 'officer@projectpulse.demo'),
      makeExpense(900000, 'Safety', 'Testing and bridge barriers', -6, 'contractor@projectpulse.demo'),
    ],
    risk: {
      level: 'Critical',
      score: 94,
      reasons: ['Bridge deck work is behind schedule', 'Structural quality issue requires rework', 'Multiple critical issues remain unresolved'],
      daysRemaining: 18,
      delayDays: 15,
      unresolvedIssues: 2,
    },
  },
  {
    id: 'p-109',
    projectCode: 'PP-109',
    name: 'IT Classroom Modernization',
    description: 'Upgrade college classrooms with digital boards and internet connectivity.',
    department: 'Higher Education',
    category: 'Academic Infrastructure',
    state: 'Karnataka',
    district: 'Mysuru',
    location: 'Nanjangud',
    latitude: 12.1185,
    longitude: 76.6953,
    budget: 1600000,
    expenditure: 980000,
    progress: 84,
    status: 'In Progress',
    startDate: iso(-150),
    expectedEndDate: iso(8),
    actualEndDate: undefined,
    managerId: 'u-officer',
    contractorId: 'u-contractor',
    createdAt: iso(-170),
    milestones: [
      makeMilestone('Cable Layout', 'Network cabling and classroom mapping', -130, -100, 100, 'Completed', 'IT Team'),
      makeMilestone('AV Setup', 'Smart boards and projectors', -60, -10, 82, 'In Progress', 'Contractor'),
      makeMilestone('Network Testing', 'Connectivity and user testing', 0, 20, 40, 'Pending', 'Officer'),
    ],
    issues: [
      makeIssue('Cable routing mismatch', 'A few classrooms need additional duct work', 'Low', 'Resolved', 'Officer', -8, 'Resolved during inspection'),
    ],
    documents: [
      makeDocument('Network Layout', 'https://example.com/college-network.pdf', 'officer@projectpulse.demo', -140),
      makeDocument('Delivery Slip', 'https://example.com/college-delivery.pdf', 'contractor@projectpulse.demo', -12),
    ],
    progressUpdates: [
      makeProgressUpdate(78, 'Smart boards installed in 5 classrooms', 'https://images.unsplash.com/...', 'contractor@projectpulse.demo', -7),
      makeProgressUpdate(84, 'Network final testing in progress', 'https://images.unsplash.com/...', 'officer@projectpulse.demo', -2),
    ],
    expenses: [
      makeExpense(420000, 'Smart Boards', 'Interactive display units', -80, 'officer@projectpulse.demo'),
      makeExpense(280000, 'Networking', 'Cabling and routers', -20, 'contractor@projectpulse.demo'),
      makeExpense(240000, 'Lab', 'Support equipment and installation', -9, 'officer@projectpulse.demo'),
    ],
    risk: {
      level: 'Low',
      score: 24,
      reasons: ['Installation is mostly complete and minor testing remains'],
      daysRemaining: 8,
      delayDays: 1,
      unresolvedIssues: 0,
    },
  },
  {
    id: 'p-110',
    projectCode: 'PP-110',
    name: 'Public Toilet Block Upgrade',
    description: 'Upgrade sanitation blocks in a busy market and transit hub area.',
    department: 'Sanitation',
    category: 'Public Amenities',
    state: 'Delhi',
    district: 'New Delhi',
    location: 'Rohini Sector 3',
    latitude: 28.7385,
    longitude: 77.0969,
    budget: 1700000,
    expenditure: 1520000,
    progress: 66,
    status: 'Not Started',
    startDate: iso(-40),
    expectedEndDate: iso(70),
    actualEndDate: undefined,
    managerId: 'u-officer',
    contractorId: 'u-contractor',
    createdAt: iso(-50),
    milestones: [
      makeMilestone('Design Approval', 'Review and approval of sanitation layout', -30, -10, 100, 'Completed', 'Officer'),
      makeMilestone('Procurement', 'Fixtures and plumbing materials', -5, 25, 25, 'Pending', 'Contractor'),
      makeMilestone('Installation', 'Plumbing and civil work', 20, 80, 0, 'Pending', 'Contractor'),
    ],
    issues: [
      makeIssue('Procurement timing issue', 'Materials need approval before release', 'Medium', 'Open', 'Officer', -2),
    ],
    documents: [
      makeDocument('Sanctioned Estimate', 'https://example.com/toilet-estimate.pdf', 'officer@projectpulse.demo', -35),
      makeDocument('Vendor Quotation', 'https://example.com/toilet-vendor.pdf', 'contractor@projectpulse.demo', -18),
    ],
    progressUpdates: [
      makeProgressUpdate(15, 'Project approved and materials ordering initiated', 'https://images.unsplash.com/...', 'officer@projectpulse.demo', -7),
      makeProgressUpdate(66, 'Procurement under review pending final approval', 'https://images.unsplash.com/...', 'contractor@projectpulse.demo', -3),
    ],
    expenses: [
      makeExpense(440000, 'Materials', 'Fixtures and plumbing supplies', -15, 'officer@projectpulse.demo'),
      makeExpense(290000, 'Civil', 'Concrete and structural works', -9, 'officer@projectpulse.demo'),
    ],
    risk: {
      level: 'Medium',
      score: 51,
      reasons: ['Procurement approval still pending', 'Installation has not begun'],
      daysRemaining: 70,
      delayDays: 4,
      unresolvedIssues: 1,
    },
  },
];

export const demoAlerts: AlertItem[] = [
  {
    id: 'a-1',
    title: 'Milestone Deadline Crossed',
    message: 'Rural Road Development Project #101 has exceeded its milestone deadline by 12 days.',
    type: 'critical',
    isRead: false,
    createdAt: iso(-2),
  },
  {
    id: 'a-2',
    title: 'Budget Threshold Warning',
    message: 'Solar Street Lighting Project is approaching budget utilization threshold.',
    type: 'warning',
    isRead: false,
    createdAt: iso(-4),
  },
  {
    id: 'a-3',
    title: 'Progress Update Missing',
    message: 'Community Hall Development has not received a field update in 14 days.',
    type: 'info',
    isRead: true,
    createdAt: iso(-8),
  },
  {
    id: 'a-4',
    title: 'Critical Issue Spotted',
    message: 'Rural Bridge Construction has a critical quality concern requiring review.',
    type: 'critical',
    isRead: false,
    createdAt: iso(-1),
  },
];

export const demoFeedback: ProjectFeedback[] = [
  {
    id: 'f-1',
    projectId: 'p-101',
    name: 'Anita Rao',
    email: 'anita@example.com',
    category: 'Delay',
    description: 'The road construction has been delayed and drainage work is incomplete near the school crossing.',
    imageUrl: 'https://images.unsplash.com/photo-1504307651254-35680f356dfd',
    status: 'Pending Review',
    createdAt: iso(-9),
    location: 'Kanakapura Road',
  },
  {
    id: 'f-2',
    projectId: 'p-104',
    name: 'Laxman Iyer',
    email: 'laxman@example.com',
    category: 'Work quality',
    description: 'The new health centre premises look well planned and the facility is clean.',
    status: 'Reviewed',
    createdAt: iso(-20),
    location: 'Sinnar',
  },
  {
    id: 'f-3',
    projectId: 'p-107',
    name: 'Ritika Sen',
    email: 'ritika@example.com',
    category: 'Safety',
    description: 'Drainage trench on the main road is not securely barricaded during work hours.',
    status: 'Pending Review',
    createdAt: iso(-3),
    location: 'Bidhannagar',
  },
];

export const demoSummary = {
  totalProjects: demoProjects.length,
  activeProjects: demoProjects.filter((project) => project.status === 'In Progress').length,
  completedProjects: demoProjects.filter((project) => project.status === 'Completed').length,
  delayedProjects: demoProjects.filter((project) => project.status === 'Delayed').length,
  totalBudget: demoProjects.reduce((sum, project) => sum + project.budget, 0),
  totalExpenditure: demoProjects.reduce((sum, project) => sum + project.expenditure, 0),
  averageCompletion: Math.round(demoProjects.reduce((sum, project) => sum + project.progress, 0) / demoProjects.length),
};

const oneMonthAgo = new Date();
oneMonthAgo.setMonth(oneMonthAgo.getMonth() - 1);
export const demoReports = [
  {
    id: 'r-1',
    title: 'Monthly Progress Snapshot',
    generatedAt: oneMonthAgo.toISOString(),
    type: 'Project Progress',
  },
  {
    id: 'r-2',
    title: 'Budget Utilization Summary',
    generatedAt: new Date().toISOString(),
    type: 'Financial',
  },
];
